//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account System.
        /// </summary>
        public static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting System.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Status.
        /// </summary>
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc With Stock.
        /// </summary>
        public static string AccWithStock {
            get {
                return ResourceManager.GetString("AccWithStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string AccYear {
            get {
                return ResourceManager.GetString("AccYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active System.
        /// </summary>
        public static string ActiveSystem {
            get {
                return ResourceManager.GetString("ActiveSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This system already exist for same domain.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arb Msg.
        /// </summary>
        public static string ArbMsg {
            get {
                return ResourceManager.GetString("ArbMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArbName {
            get {
                return ResourceManager.GetString("ArbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AreaSize.
        /// </summary>
        public static string AreaSize {
            get {
                return ResourceManager.GetString("AreaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        public static string Bathroom {
            get {
                return ResourceManager.GetString("Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broad Cast.
        /// </summary>
        public static string BroadCast {
            get {
                return ResourceManager.GetString("BroadCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string c_Company {
            get {
                return ResourceManager.GetString("c_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string c_FirstName {
            get {
                return ResourceManager.GetString("c_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string c_Gender {
            get {
                return ResourceManager.GetString("c_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Test.
        /// </summary>
        public static string c_is_test {
            get {
                return ResourceManager.GetString("c_is_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string c_LastName {
            get {
                return ResourceManager.GetString("c_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string c_Mobile {
            get {
                return ResourceManager.GetString("c_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration By.
        /// </summary>
        public static string c_RegistrationBy {
            get {
                return ResourceManager.GetString("c_RegistrationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string c_RegistrationDate {
            get {
                return ResourceManager.GetString("c_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upadte Date.
        /// </summary>
        public static string c_UpadteDate {
            get {
                return ResourceManager.GetString("c_UpadteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        public static string c_UpdateBy {
            get {
                return ResourceManager.GetString("c_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Client Password.
        /// </summary>
        public static string ChangeUserPassword {
            get {
                return ResourceManager.GetString("ChangeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Domain.
        /// </summary>
        public static string CoDomain {
            get {
                return ResourceManager.GetString("CoDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Guid.
        /// </summary>
        public static string CoGuid {
            get {
                return ResourceManager.GetString("CoGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Active System.
        /// </summary>
        public static string CompanyActiveSys {
            get {
                return ResourceManager.GetString("CompanyActiveSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Database.
        /// </summary>
        public static string CompanyDB {
            get {
                return ResourceManager.GetString("CompanyDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Domain.
        /// </summary>
        public static string CompanyDomain {
            get {
                return ResourceManager.GetString("CompanyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirmnewpassword {
            get {
                return ResourceManager.GetString("Confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact tUs.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of error in your information please contact us.
        /// </summary>
        public static string ContactUsMsg {
            get {
                return ResourceManager.GetString("ContactUsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Value.
        /// </summary>
        public static string ContactValue {
            get {
                return ResourceManager.GetString("ContactValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont End Date.
        /// </summary>
        public static string ContEndDate {
            get {
                return ResourceManager.GetString("ContEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Cost.
        /// </summary>
        public static string ContractCost {
            get {
                return ResourceManager.GetString("ContractCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Info.
        /// </summary>
        public static string ContractInfo {
            get {
                return ResourceManager.GetString("ContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont Start Date.
        /// </summary>
        public static string ContStartDate {
            get {
                return ResourceManager.GetString("ContStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Company.
        /// </summary>
        public static string CreateNewCompany {
            get {
                return ResourceManager.GetString("CreateNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Kind.
        /// </summary>
        public static string CreateNewKind {
            get {
                return ResourceManager.GetString("CreateNewKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company is being set up.
        /// </summary>
        public static string CreateYourCompany {
            get {
                return ResourceManager.GetString("CreateYourCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng.
        /// </summary>
        public static string CurLang {
            get {
                return ResourceManager.GetString("CurLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string CustMsg {
            get {
                return ResourceManager.GetString("CustMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, please enter your contact information to improve the quality of our services and ease of communication with you.
        /// </summary>
        public static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Under Processing.
        /// </summary>
        public static string DataUnderProcessing {
            get {
                return ResourceManager.GetString("DataUnderProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Activate.
        /// </summary>
        public static string DeActivate {
            get {
                return ResourceManager.GetString("DeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Dir {
            get {
                return ResourceManager.GetString("Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail not a valid domain for your company!.
        /// </summary>
        public static string EmailNotValidDomain {
            get {
                return ResourceManager.GetString("EmailNotValidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Login.
        /// </summary>
        public static string EmpLogin {
            get {
                return ResourceManager.GetString("EmpLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Table.
        /// </summary>
        public static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng Msg.
        /// </summary>
        public static string EngMsg {
            get {
                return ResourceManager.GetString("EngMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EngName {
            get {
                return ResourceManager.GetString("EngName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للدعم الفني .
        /// </summary>
        public static string ForOurSupport {
            get {
                return ResourceManager.GetString("ForOurSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Support Please contact us :.
        /// </summary>
        public static string ForSupport {
            get {
                return ResourceManager.GetString("ForSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Estate Guid.
        /// </summary>
        public static string FRealEstGuid {
            get {
                return ResourceManager.GetString("FRealEstGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Estate Kind Id.
        /// </summary>
        public static string FREKId {
            get {
                return ResourceManager.GetString("FREKId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit-Kind Id.
        /// </summary>
        public static string FUnitKindId {
            get {
                return ResourceManager.GetString("FUnitKindId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resourse .
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources System.
        /// </summary>
        public static string HummanResourece {
            get {
                return ResourceManager.GetString("HummanResourece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string IdentityID {
            get {
                return ResourceManager.GetString("IdentityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string InfoEmpty {
            get {
                return ResourceManager.GetString("InfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string InfoFiltered {
            get {
                return ResourceManager.GetString("InfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory System.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string LeftRight {
            get {
                return ResourceManager.GetString("LeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string LengthMenu {
            get {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Get Started.
        /// </summary>
        public static string LetsGetStarted {
            get {
                return ResourceManager.GetString("LetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking your Data.
        /// </summary>
        public static string LoadingMsg {
            get {
                return ResourceManager.GetString("LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Record.
        /// </summary>
        public static string LoginRecord {
            get {
                return ResourceManager.GetString("LoginRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one point of sale.
        /// </summary>
        public static string MessagePleaseChooseOneCompanySys {
            get {
                return ResourceManager.GetString("MessagePleaseChooseOneCompanySys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modal-left.
        /// </summary>
        public static string ModalDir {
            get {
                return ResourceManager.GetString("ModalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modal-right.
        /// </summary>
        public static string ModalDirX {
            get {
                return ResourceManager.GetString("ModalDirX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Login Logs.
        /// </summary>
        public static string MyLoginLog {
            get {
                return ResourceManager.GetString("MyLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Newpassword {
            get {
                return ResourceManager.GetString("Newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Days.
        /// </summary>
        public static string NotificationDays {
            get {
                return ResourceManager.GetString("NotificationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed Successfully.
        /// </summary>
        public static string OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Value.
        /// </summary>
        public static string PaidValue {
            get {
                return ResourceManager.GetString("PaidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Does Not Match.
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add A Password.
        /// </summary>
        public static string PleaseAddAPassword {
            get {
                return ResourceManager.GetString("PleaseAddAPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleasefillalRequiredfields.
        /// </summary>
        public static string PleasefillalRequiredfields {
            get {
                return ResourceManager.GetString("PleasefillalRequiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Unit Kind.
        /// </summary>
        public static string PlsSelectUnitKind {
            get {
                return ResourceManager.GetString("PlsSelectUnitKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Of Sale System.
        /// </summary>
        public static string PointSale {
            get {
                return ResourceManager.GetString("PointSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Of Sale.
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Data.
        /// </summary>
        public static string PreparingData {
            get {
                return ResourceManager.GetString("PreparingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Estate.
        /// </summary>
        public static string RealEstate {
            get {
                return ResourceManager.GetString("RealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate Kind.
        /// </summary>
        public static string RealEstateKind {
            get {
                return ResourceManager.GetString("RealEstateKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Kind.
        /// </summary>
        public static string RentKind {
            get {
                return ResourceManager.GetString("RentKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Permissions.
        /// </summary>
        public static string SaveRole {
            get {
                return ResourceManager.GetString("SaveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcom To SeniorsSoft.
        /// </summary>
        public static string SignintoSeniorsSoft {
            get {
                return ResourceManager.GetString("SignintoSeniorsSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somthing Went Wrong.
        /// </summary>
        public static string SomthingWentWrong {
            get {
                return ResourceManager.GetString("SomthingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate to sort column ascending :.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate to sort column descending :.
        /// </summary>
        public static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Activate Client.
        /// </summary>
        public static string StopActivateClient {
            get {
                return ResourceManager.GetString("StopActivateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Date.
        /// </summary>
        public static string StopDate {
            get {
                return ResourceManager.GetString("StopDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, your account has been suspended.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for suspension.
        /// </summary>
        public static string SuspNote {
            get {
                return ResourceManager.GetString("SuspNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Kind.
        /// </summary>
        public static string SysKind {
            get {
                return ResourceManager.GetString("SysKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Country.
        /// </summary>
        public static string SystemContry {
            get {
                return ResourceManager.GetString("SystemContry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for contacting us you will be replied to soon.
        /// </summary>
        public static string thankcontactUs {
            get {
                return ResourceManager.GetString("thankcontactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Change Domain Name.
        /// </summary>
        public static string ThisDomainExist {
            get {
                return ResourceManager.GetString("ThisDomainExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Attendance System.
        /// </summary>
        public static string TimeAttend {
            get {
                return ResourceManager.GetString("TimeAttend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit-Count.
        /// </summary>
        public static string UnitCount {
            get {
                return ResourceManager.GetString("UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Kind.
        /// </summary>
        public static string UnitKind {
            get {
                return ResourceManager.GetString("UnitKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Database.
        /// </summary>
        public static string UpdateDatabase {
            get {
                return ResourceManager.GetString("UpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Logs.
        /// </summary>
        public static string UserLoginLogs {
            get {
                return ResourceManager.GetString("UserLoginLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Logs.
        /// </summary>
        public static string UserLoingLogs {
            get {
                return ResourceManager.GetString("UserLoingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vmarket.
        /// </summary>
        public static string Vmarket {
            get {
                return ResourceManager.GetString("Vmarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Records.
        /// </summary>
        public static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
